FROM python:3.10.15

ADD . /ml_pipeline

WORKDIR /ml_pipeline

RUN apt -q -qq update && \
  DEBIAN_FRONTEND=noninteractive apt install -y \
  software-properties-common \
  wget

RUN apt-get update && \
  apt-get upgrade -y && \
  apt-get install -y git

RUN apt-get update -y && \
    pip install -r requirements.txt

RUN apt-get autoremove -yqq --purge && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["python","occupancy.py"]